Notes.Web/Controllers/NoteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Notes.BLL.Services.CurrentUserAccessor.Exceptions;
using Notes.BLL.Services.MarkdownRendererService;
using Notes.BLL.Services.NoteManagers;
using Notes.BLL.Services.NoteManagers.Enums;
using Notes.BLL.Services.NoteManagers.Exceptions;
using Notes.BLL.Services.NoteManagers.Models;
using Notes.Web.Enums;
using Notes.Web.Models.Note;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Notes.Web.Controllers
{
    [Authorize]
    public class NoteController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMarkdownRenderer _markdownRenderer;
        private readonly INoteManager _noteManager;
        private readonly ILogger<NoteController> _logger;

        public NoteController(INoteManager notesManager, IMapper mapper, IMarkdownRenderer markdownRenderer, ILogger<NoteController> logger)
        {
            _noteManager = notesManager;
            _mapper = mapper;
            _markdownRenderer = markdownRenderer;
            _logger = logger;
        }

        [HttpGet]
        public ActionResult NoteList(NoteListViewModel model)
        {
            _logger.LogDebug($"\"NoteList\" action method called");

            const int NotesInPage = 10;

            IEnumerable<Note> notes;

            if (model.SearchFilter == null)
            {
                notes = _noteManager.GetAllNotes();
            }
            else
            {
                var filter = _mapper.Map<SearchFilter>(model.SearchFilter);

                notes = _noteManager.GetAllByFilter(filter);
            }

            var tags = _noteManager.GetAllTags();


            int page = model.CurrentPage <= 0 ? 1 : model.CurrentPage;

            int lastPage = (int)Math.Ceiling((float)notes.Count() / NotesInPage);

            int currentPage = page <= lastPage || lastPage <= 0 ? page : lastPage;

            IEnumerable<ReadNoteViewModel> notesForCurrentPage = _mapper.Map<List<ReadNoteViewModel>>(notes);

            switch (model.Ordering)
            {
                case NotesOrdering.None:
                    break;
                case NotesOrdering.ByTitleAlphabetically:
                    notesForCurrentPage = notesForCurrentPage.OrderBy(n => n.Title);
                    break;
                case NotesOrdering.ByCreatedDate:
                    notesForCurrentPage = notesForCurrentPage.OrderBy(n => n.CreatedDate);
                    break;
                case NotesOrdering.ByTitleReverseAlphabetically:
                    notesForCurrentPage = notesForCurrentPage.OrderByDescending(n => n.Title);
                    break;
                case NotesOrdering.ByCreatedDateReverse:
                    notesForCurrentPage = notesForCurrentPage.OrderByDescending(n => n.CreatedDate);
                    break;
                default:
                    throw new NotImplementedException();
            }

            notesForCurrentPage = notesForCurrentPage.Skip((currentPage - 1) * NotesInPage)
                .Take(NotesInPage);

            var viewModel = new NoteListViewModel()
            {
                Notes = notesForCurrentPage,
                CurrentPage = currentPage,
                LastPage = lastPage,
                AllTags = _mapper.Map<List<string>>(tags),
                SearchFilter = model.SearchFilter,
            };

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            _logger.LogDebug($"\"Create\" action method called");

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(NoteCreateViewModel model)
        {
            _logger.LogDebug($"\"Create\" action method called");

            var note = _mapper.Map<NoteCreateData>(model);

            try
            {
                await _noteManager.CreateNewNoteAsync(note);

                return View();
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public ActionResult EditNote(int id)
        {
            _logger.LogDebug($"\"EditNote\" action method called");

            try
            {
                var note = _noteManager.GetNoteById(id);

                var viewModel = _mapper.Map<EditNoteViewModel>(note);

                viewModel.AllTags = GetAllTagsForCurrentUser();
            
                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<ActionResult> EditNote(EditNoteViewModel viewModel)
        {
            _logger.LogDebug($"\"EditNote\" action method called");

            try
            {
                if (ModelState.IsValid == true)
                {
                    var note = _mapper.Map<NoteUpdateData>(viewModel);

                    await _noteManager.UpdateNoteAsync(note);

                    return RedirectToAction(nameof(Read), new { id = viewModel.Id });
                }

                var model = _noteManager.GetNoteById(viewModel.Id);

                viewModel = _mapper.Map<EditNoteViewModel>(model);
            
                viewModel.AllTags = GetAllTagsForCurrentUser();

                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        private IEnumerable<TagItemViewModel> GetAllTagsForCurrentUser()
        {
            _logger.LogDebug($"\"GetAllTagsForCurrentUser\" action method called");

            var allTags = _noteManager.GetAllTags();

            var allViewModelTags = _mapper.Map<IEnumerable<Tag>, List<TagItemViewModel>>(allTags);

            return allViewModelTags;
        }

        [HttpGet]
        public IActionResult Read(int id)
        {
            _logger.LogDebug($"\"Read\" action method called");

            try
            {
                var note = _noteManager.GetNoteById(id);

                var viewModel = _mapper.Map<ReadNoteViewModel>(note);

                var html = _markdownRenderer.RenderFromMarkdownToHTML(note.Text);

                viewModel.HtmlText = html;

                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public IActionResult AddTagToNote(int noteId, int tagId)
        {
            _logger.LogDebug($"\"AddTagToNote\" action method called");

            try
            {
                _noteManager.AddTagToNote(noteId, tagId);

                return RedirectToActionPermanent("EditNote", new { id = noteId });
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }
        
        [HttpPost]
        public IActionResult RemoveTagFromNote(int noteId, int tagId)
        {
            _logger.LogDebug($"\"RemoveTagFromNote\" action method called");

            try
            {
                _noteManager.RemoveTagFromNote(noteId, tagId);

                return RedirectToActionPermanent("EditNote", new { id = noteId });
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }


        [HttpGet]
        public IActionResult TagList()
        {
            _logger.LogDebug($"\"TagList\" action method called");

            try
            {
                var tags = _noteManager.GetAllTags();

                var tagViewModels = _mapper.Map<IEnumerable<Tag>, List<TagItemViewModel>>(tags); 
                
                var viewModel = new TagListViewModel() { AllTags = tagViewModels };

                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {

Notes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notes.Web</title>

    <link rel="stylesheet" href="~/css/markdownStyles.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Notes.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Info">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="NoteList">My notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="ImportantNoteList">Important</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Create">Add new note</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="TagList">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Notes.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>