Notes.Web/Models/EditNoteViewModel.cs
using System.Collections.Generic;

namespace Notes.Web.Models
{
    public class EditNoteViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public IEnumerable<TagItemViewModel> AllTags { get; set; }
        public IEnumerable<TagItemViewModel> Tags { get; set; }
    }
}

Notes.Web/Models/EditTagsViewModel.cs
using System.Collections.Generic;

namespace Notes.Web.Models
{
    public class TagListViewModel
    {
        public IEnumerable<TagViewModel> AllTags { get; set; }
    }
}

Notes.Web/Models/Note/EditNoteViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Notes.Web.Models.Note
{
    public class EditNoteViewModel
    {
        [Required]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Text { get; set; }
        public bool IsImportant { get; set; }
        public IEnumerable<TagItemViewModel>? AllTags { get; set; }
        public IEnumerable<TagItemViewModel>? Tags { get; set; }
    }
}

Notes.Web/Models/Note/FilterSettings.cs
using System.Collections.Generic;

namespace Notes.Web.Models.Note
{
    public class FilterSettings
    {
        public string Name { get; set; }
        public string Text { get; set; }
        public IEnumerable<string> Tags { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
        public bool IsImportant { get; set; }
    }
}

Notes.Web/Models/Note/NoteCreateViewModel.cs
namespace Notes.Web.Models.Note
{
    public class NoteCreateViewModel
    {
        public string? Title { get; set; }
        public string? Text { get; set; }
    }
}

Notes.Web/Models/Note/NoteListViewModel.cs
using Notes.Web.Enums;
using System.Collections.Generic;

namespace Notes.Web.Models.Note
{
    public class NoteListViewModel
    {
        public int CurrentPage { get; set; }

        public int LastPage { get; set; }

        public IEnumerable<ReadNoteViewModel>? Notes { get; set; }

        public IEnumerable<string>? AllTags { get; set; }

        public NotesOrdering Ordering { get; set; }

        public SearchFilterViewModel? SearchFilter { get; set; }
    }
}

Notes.Web/Models/Note/PartialStarViewModel.cs
namespace Notes.Web.Models.Note
{
    public class PartialStarViewModel
    {
        public int Id { get; set; }
        public string? ReturnURL { get; set; }
        public bool IsImportant { get; set; }
    }
}

Notes.Web/Models/Note/ReadNoteViewModel.cs
using Microsoft.AspNetCore.Html;
using Notes.BLL.Services.NoteManagers.Models;
using System;
using System.Collections.Generic;

namespace Notes.Web.Models.Note
{
    public class ReadNoteViewModel
    {
        public int Length 
        {
            get => Text != null ? Text.Length : 0; 
        }
        public int LineCount 
        {
            get => Text != null ? Text.Split('\n').Length : 0;
        }
        
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Text { get; set; }
        public bool IsImportant { get; set; }
        public DateTime CreatedDate { get; set; }
        public IHtmlContent? HtmlText { get; set; }
        public IEnumerable<TagItemViewModel>? Tags { get; set; }
    }
}

Notes.Web/Models/Note/SearchFilterViewModel.cs
using Notes.Web.Enums;
using System.Collections.Generic;

namespace Notes.Web.Models.Note
{
    public class SearchFilterViewModel
    {
        public string? Title { get; set; }
        public string? Text { get; set; }
        public IEnumerable<string>? Tags { get; set; }
        public bool UseMinLength { get; set; } = false;
        public bool UseMaxLength { get; set; } = false;
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
        public Importance Importance { get; set; }
    }
}

Notes.Web/Models/Note/TagItemViewModel.cs
namespace Notes.Web.Models.Note
{
    public class TagItemViewModel
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int NotesCount { get; set; }
    }
}

Notes.Web/Models/Note/TagListViewModel.cs
using System.Collections.Generic;

namespace Notes.Web.Models.Note
{
    public class TagListViewModel
    {
        public IEnumerable<TagItemViewModel>? AllTags { get; set; }
    }
}

Notes.Web/Models/TagListViewModel.cs
using System.Collections.Generic;

namespace Notes.Web.Models
{
    public class TagListViewModel
    {
        public IEnumerable<TagItemViewModel> AllTags { get; set; }
    }
}

Notes.Web/Controllers/NotesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Notes.BLL.Services.CurrentUserAccessor.Exceptions;
using Notes.BLL.Services.MarkdownRendererService;
using Notes.BLL.Services.NoteManagers;
using Notes.BLL.Services.NoteManagers.Exceptions;
using Notes.BLL.Services.NoteManagers.Models;
using Notes.Web.Models.Note;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Notes.Web.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMarkdownRenderer _markdownRenderer;
        private readonly INoteManager _noteManager;

        public NotesController(INoteManager notesManager, IMapper mapper, IMarkdownRenderer markdownRenderer)
        {
            _noteManager = notesManager;
            _mapper = mapper;
            _markdownRenderer = markdownRenderer;
        }

        [HttpGet]
        public ActionResult NoteList(int page = 1)
        {
            const int NotesInPage = 2;

            IEnumerable<Note> notes = _noteManager.GetAllNotes();

            var notesForPage = notes.Skip((page - 1) * NotesInPage)
                .Take(NotesInPage);

            var viewModel = _mapper.Map<IEnumerable<Note>, NoteListViewModel>(notesForPage);

            viewModel.CurrentPage = page;
            viewModel.LastPage = (int) Math.Ceiling((float) notes.Count() / NotesInPage);

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(NoteCreateViewModel model)
        {
            var note = _mapper.Map<NoteCreateData>(model);

            try
            {
                await _noteManager.CreateNewNoteAsync(note);

                return View();
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public ActionResult EditNote(int id)
        {
            try
            {
                var note = _noteManager.GetNoteById(id);

                var viewModel = _mapper.Map<EditNoteViewModel>(note);

                viewModel.AllTags = GetAllTagsForCurrentUser();
            
                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<ActionResult> EditNote(EditNoteViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    var note = _mapper.Map<NoteUpdateData>(viewModel);

                    await _noteManager.UpdateNoteAsync(note);

                    return RedirectToAction(nameof(Read), new { id = viewModel.Id });
                }

                var model = _noteManager.GetNoteById(viewModel.Id);

                viewModel = _mapper.Map<EditNoteViewModel>(model);
            
                viewModel.AllTags = GetAllTagsForCurrentUser();

                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        private IEnumerable<TagItemViewModel> GetAllTagsForCurrentUser()
        {
            var allTags = _noteManager.GetAllTags();

            var allViewModelTags = _mapper.Map<IEnumerable<Tag>, List<TagItemViewModel>>(allTags);

            return allViewModelTags;
        }

        [HttpGet]
        public IActionResult Read(int id)
        {
            try
            {
                var note = _noteManager.GetNoteById(id);

                var viewModel = _mapper.Map<ReadNoteViewModel>(note);

                var html = _markdownRenderer.RenderFromMarkdownToHTML(note.Text);

                viewModel.HtmlText = html;

                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public IActionResult AddTagToNote(int noteId, int tagId)
        {
            try
            {
                _noteManager.AddTagToNote(noteId, tagId);

                return RedirectToActionPermanent("EditNote", new { id = noteId });
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }
        
        [HttpPost]
        public IActionResult RemoveTagFromNote(int noteId, int tagId)
        {
            try
            {
                _noteManager.RemoveTagFromNote(noteId, tagId);

                return RedirectToActionPermanent("EditNote", new { id = noteId });
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }


        [HttpGet]
        public IActionResult TagList()
        {
            try
            {
                var tags = _noteManager.GetAllTags();

                var tagViewModels = _mapper.Map<IEnumerable<Tag>, List<TagItemViewModel>>(tags); 
                
                var viewModel = new TagListViewModel() { AllTags = tagViewModels };

                return View(viewModel);
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddNewTag(string tagName)
        {
            try
            {
                var tag = new TagCreateData() { Name = tagName };

                await _noteManager.AddTagAsync(tag);

                return RedirectToActionPermanent("TagList");
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public IActionResult DeleteTag(int id)
        {
            try
            {
                _noteManager.DeleteTagById(id);

                return RedirectToActionPermanent("TagList");
            }
            catch (NotAuthorizedException)
            {
                return RedirectToAction("Register", "Account");
            }
            catch (NotFoundException)
            {
                return StatusCode(404);
            }
            catch (UserAccessException)
            {
                return StatusCode(403);
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

Notes.Web/Views/Notes/Create.cshtml
@model NoteCreateViewModel

<button id="addTagButton">Add tag</button>
<form method="post" asp-action="Create" asp-controller="Notes">
    <div class="form-group">
        <label>Title</label>
        <input class="form-control" type="text" asp-for="Title"/>
    </div>

    <div class="form-group">
        <label>Text</label>
        <textarea class="form-control" rows="9" asp-for="Text"></textarea>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">Save</button>
    </div>
</form>

Notes.Web/Views/Notes/EditNote.cshtml
@model EditNoteViewModel

<form method="post" asp-controller="Notes" asp-action="AddTagToNote">
    <div class="form-group">
        <select class="form-select" name="tagId">
            @foreach (var tag in Model.AllTags)
            {
                <option value="@tag.Id">
                    @tag.Name
                </option>
            }
        </select>
        <a class="btn btn-success" asp-action="TagList" asp-controller="Notes">Create more tags</a>

    </div>

    <input hidden name="noteId" type="number" value="@Model.Id"/>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">
            Add tag
        </button>
    </div>
</form>

<div class="flex-wrap row gy-5">
    @foreach (var tag in Model.Tags)
    {
        <form asp-controller="Notes" asp-action="RemoveTagFromNote" method="post">
            <div class="m-3 d-inline card">
                #@tag.Name
                <button>
                    <span>&times;</span>
                </button>
            </div>
            
            <input hidden value="@Model.Id" name="noteId">
            <input hidden value="@tag.Id" name="tagId">
        </form>
    }
</div>

<form asp-controller="Notes" asp-action="EditNote" method="post">
    <div class="form-group">
        <label>Title</label>
        <input class="form-control" type="text" asp-for="Title"/>
    </div>

    <div class="form-group">
        <label>Text</label>
        <textarea class="form-control" rows="9" asp-for="Text"></textarea>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">Save</button>
    </div>

    <input type="hidden" asp-for="Id" value="@Model.Id"/>
</form>

Notes.Web/Views/Notes/EditTags.cshtml
@model EditTagsViewModel

<div class="m-1">
    <div class="flex-wrap row gy-5">
        <form asp-controller="Notes" asp-action="DeleteTag" method="post">
            @foreach (var tag in Model.AllTags)
            {
                <div class="p-1 m-2 d-inline card">
                    #@tag.Name
                    <span class="badge bg-primary rounded-pill">@tag.NotesCount</span>
                    <button onClick="return confirm('This tag has been using in @tag.NotesCount notes');"
                        class="btn btn-danger rounded-pill btn-sm" value="@tag.Id" name="id">
                        <span>&times;</span>
                    </button>
                </div>
            }
        </form>
    </div>


    <form asp-controller="Notes" asp-action="AddNewTag" method="post">
        <div class="m-1">
            <label>Tag name:</label>
        </div>

        <div class="m-1">
            <input class="form-control" name="tagName" type="text"/>
        </div>
        
        <div class="m-1">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

Notes.Web/Views/Notes/Read.cshtml
@model ReadNoteViewModel

<div class="flex-wrap row gy-5">
    @foreach (var tag in Model.Tags)
    {
        <div class="m-3 d-inline card">
            #@tag.Name
        </div>
    }
</div>
    
<div class="modal-content rounded-4 shadow">
    <div class="modal-header border-bottom-0">
        <h1>
            @Model.Title
        </h1>
    </div>
    <div class="modal-body py-0">
        <p>
            @Model.HtmlText
        </p>
    </div>
</div>
<div class="mt-2">
    <a class="btn btn-primary"
       asp-controller="Notes" asp-action="EditNote" asp-route-id="@Model.Id">
        Edit
    </a>
</div>

Notes.Web/Views/Notes/ShowAll.cshtml
@model IEnumerable<NoteViewModel>
<ul>
    <li class="list-group">
        @foreach (var note in Model)
        {
            <div class="mt-1">
                <a asp-controller="Notes" asp-action="Read" asp-route-id="@note.Id"
                    class="list-group-item list-group-item-action">
                    <strong>@note.Title</strong>
                </a>
            </div>
        }
    </li>
</ul>

Notes.Web/Views/Notes/TagList.cshtml
@model TagListViewModel

<div class="m-1">
    <div class="flex-wrap row gy-5">
        <form asp-controller="Notes" asp-action="DeleteTag" method="post">
            @foreach (var tag in Model.AllTags)
            {
                <div class="p-1 m-2 d-inline card">
                    #@tag.Name
                    <span class="badge bg-primary rounded-pill">@tag.NotesCount</span>
                    <button onClick="return confirm('This tag has been using in @tag.NotesCount notes');"
                        class="btn btn-danger rounded-pill btn-sm" value="@tag.Id" name="id">
                        <span>&times;</span>
                    </button>
                </div>
            }
        </form>
    </div>


    <form asp-controller="Notes" asp-action="AddNewTag" method="post">
        <div class="m-1">
            <label>Tag name:</label>
        </div>

        <div class="m-1">
            <input class="form-control" name="tagName" type="text"/>
        </div>
        
        <div class="m-1">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

Notes.Web/Views/Notes/Update.cshtml
@model UpdateNoteViewModel

<form method="post" asp-controller="Notes" asp-action="AddTagToNote">
    <div class="form-group">
        <select class="form-select" name="tagId">
            @foreach (var tag in Model.AllTags)
            {
                <option value="@tag.Id">
                    @tag.Name
                </option>
            }
        </select>
        <a class="btn btn-success" asp-action="EditTags" asp-controller="Notes">Create more tags</a>

    </div>

    <input hidden name="noteId" type="number" value="@Model.Id"/>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">
            Add tag
        </button>
    </div>
</form>

<div class="flex-wrap row gy-5">
    @foreach (var tag in Model.Tags)
    {
        <form asp-controller="Notes" asp-action="RemoveTagFromNote" method="post">
            <div class="m-3 d-inline card">
                #@tag.Name
                <button>
                    <span>&times;</span>
                </button>
            </div>
            
            <input hidden value="@Model.Id" name="noteId">
            <input hidden value="@tag.Id" name="tagId">
        </form>
    }
</div>

<form asp-controller="Notes" asp-action="Update" method="post">
    <div class="form-group">
        <label>Title</label>
        <input class="form-control" type="text" asp-for="Title"/>
    </div>

    <div class="form-group">
        <label>Text</label>
        <textarea class="form-control" rows="9" asp-for="Text"></textarea>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">Save</button>
    </div>

    <input type="hidden" asp-for="Id" value="@Model.Id"/>
</form>